import {
  Company,
  Driver,
  LatLng,
  Order,
  PackageDetails,
  RouteConflict,
  SystemEvent,
  User,
  Vehicle,
} from '../types/logistics';

export const SEED_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Logistics Operations Director',
    email: 'admin@logiroute.ai',
    role: 'admin',
    phone: '+91 98201 55432',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-customer',
    name: 'Omkar Mane',
    email: 'omkarmane512@gmail.com',
    role: 'customer',
    phone: '+91 98334 12890',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
];

export const SEED_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'SwiftShip Logistics',
    code: 'SWIFT',
    logo: '⚡',
    primaryColor: '#2563eb', // blue
    rating: 4.9,
    activeVehicles: 8,
    totalDeliveries: 1240,
    onTimeRate: 98.2,
    carbonScore: 92,
  },
  {
    id: 'comp-2',
    name: 'BlueDart Express',
    code: 'BDART',
    logo: '🔷',
    primaryColor: '#0284c7', // sky
    rating: 4.8,
    activeVehicles: 6,
    totalDeliveries: 980,
    onTimeRate: 97.5,
    carbonScore: 84,
  },
  {
    id: 'comp-3',
    name: 'Delhivery Fleet',
    code: 'DLHVY',
    logo: '🔴',
    primaryColor: '#dc2626', // red
    rating: 4.7,
    activeVehicles: 7,
    totalDeliveries: 1120,
    onTimeRate: 96.8,
    carbonScore: 81,
  },
  {
    id: 'comp-4',
    name: 'UrbanGo Logistics',
    code: 'URBN',
    logo: '🚀',
    primaryColor: '#7c3aed', // purple
    rating: 4.9,
    activeVehicles: 5,
    totalDeliveries: 760,
    onTimeRate: 98.9,
    carbonScore: 95,
  },
  {
    id: 'comp-5',
    name: 'RapidRoute Parcel',
    code: 'RAPID',
    logo: '🏁',
    primaryColor: '#ea580c', // orange
    rating: 4.6,
    activeVehicles: 4,
    totalDeliveries: 620,
    onTimeRate: 95.9,
    carbonScore: 78,
  },
  {
    id: 'comp-6',
    name: 'GreenMile EV Fleet',
    code: 'GM-EV',
    logo: '🌱',
    primaryColor: '#16a34a', // green
    rating: 4.9,
    activeVehicles: 6,
    totalDeliveries: 840,
    onTimeRate: 99.1,
    carbonScore: 99,
  },
  {
    id: 'comp-7',
    name: 'MetroParcel Co.',
    code: 'METRO',
    logo: '📦',
    primaryColor: '#0d9488', // teal
    rating: 4.7,
    activeVehicles: 4,
    totalDeliveries: 530,
    onTimeRate: 96.2,
    carbonScore: 82,
  },
  {
    id: 'comp-8',
    name: 'Apex SuperTrans',
    code: 'APEX',
    logo: '🏔️',
    primaryColor: '#4f46e5', // indigo
    rating: 4.8,
    activeVehicles: 5,
    totalDeliveries: 690,
    onTimeRate: 97.8,
    carbonScore: 86,
  },
  {
    id: 'comp-9',
    name: 'SpeedX Express',
    code: 'SPDX',
    logo: '⚡',
    primaryColor: '#d97706', // amber
    rating: 4.5,
    activeVehicles: 3,
    totalDeliveries: 410,
    onTimeRate: 94.8,
    carbonScore: 75,
  },
  {
    id: 'comp-10',
    name: 'Zenith Courier Hub',
    code: 'ZNTH',
    logo: '🎯',
    primaryColor: '#db2777', // pink
    rating: 4.8,
    activeVehicles: 4,
    totalDeliveries: 580,
    onTimeRate: 97.1,
    carbonScore: 89,
  },
];

export const LOCATION_PRESETS: { label: string; city: string; lat: number; lng: number; address: string; landmark: string }[] = [
  // Mumbai
  { label: 'Andheri West Hub', city: 'Mumbai', lat: 19.1363, lng: 72.8277, address: 'Lokhandwala Complex, Andheri West, Mumbai, MH 400053', landmark: 'Infinity Mall' },
  { label: 'Bandra Kurla Complex (BKC)', city: 'Mumbai', lat: 19.0657, lng: 72.8687, address: 'G Block, BKC Financial Center, Bandra East, Mumbai 400051', landmark: 'One BKC' },
  { label: 'Lower Parel Business Hub', city: 'Mumbai', lat: 18.9934, lng: 72.8315, address: 'Senapati Bapat Marg, Lower Parel, Mumbai 400013', landmark: 'High Street Phoenix' },
  { label: 'Powai Tech City', city: 'Mumbai', lat: 19.1176, lng: 72.9060, address: 'Hiranandani Business Park, Powai, Mumbai 400076', landmark: 'Supreme City' },
  { label: 'Nariman Point Financial Dist', city: 'Mumbai', lat: 18.9256, lng: 72.8242, address: 'Free Press Journal Marg, Nariman Point, Mumbai 400021', landmark: 'Air India Building' },
  { label: 'Dadar Central Hub', city: 'Mumbai', lat: 19.0178, lng: 72.8478, address: 'Dr. Babasaheb Ambedkar Road, Dadar TT, Mumbai 400014', landmark: 'Chitra Cinema' },
  { label: 'Navi Mumbai Vashi Hub', city: 'Mumbai', lat: 19.0771, lng: 72.9986, address: 'Sector 17, Vashi, Navi Mumbai 400703', landmark: 'Inorbit Mall Vashi' },
  { label: 'Thane West Logistics Park', city: 'Mumbai', lat: 19.2183, lng: 72.9781, address: 'Ghodbunder Road, Thane West 400607', landmark: 'Viviana Mall' },
  { label: 'Goregaon East IT Park', city: 'Mumbai', lat: 19.1663, lng: 72.8596, address: 'Nesco Center, Western Express Highway, Goregaon East 400063', landmark: 'Nesco IT Park' },
  { label: 'Kurla West Market', city: 'Mumbai', lat: 19.0726, lng: 72.8795, address: 'LBS Marg, Kurla West, Mumbai 400070', landmark: 'Phoenix Marketcity' },
  { label: 'Juhu Beach Boulevard', city: 'Mumbai', lat: 19.1075, lng: 72.8263, address: 'Juhu Tara Road, Juhu, Mumbai 400049', landmark: 'JW Marriott' },
  { label: 'Worli Seaface Estate', city: 'Mumbai', lat: 19.0166, lng: 72.8177, address: 'Khan Abdul Ghaffar Khan Road, Worli Seaface 400018', landmark: 'Worli Seaface Promenade' },
  { label: 'Malad West Infinity Zone', city: 'Mumbai', lat: 19.1860, lng: 72.8360, address: 'Link Road, Malad West, Mumbai 400064', landmark: 'Inorbit Malad' },
  { label: 'Colaba Causeway Point', city: 'Mumbai', lat: 18.9067, lng: 72.8147, address: 'Shahid Bhagat Singh Road, Colaba, Mumbai 400005', landmark: 'Gateway of India' },
  { label: 'Chembur Diamond Garden', city: 'Mumbai', lat: 19.0522, lng: 72.8994, address: 'Sion-Trombay Road, Chembur East 400071', landmark: 'Diamond Garden' },

  // Pune
  { label: 'Hinjawadi Phase 1 IT Hub', city: 'Pune', lat: 18.5913, lng: 73.7389, address: 'Rajiv Gandhi Infotech Park, Hinjawadi Phase 1, Pune 411057', landmark: 'Infosys Circle' },
  { label: 'Kothrud Central Market', city: 'Pune', lat: 18.5074, lng: 73.8077, address: 'Paud Road, Kothrud, Pune 411038', landmark: 'Chandani Chowk' },
  { label: 'Viman Nagar Commerce Zone', city: 'Pune', lat: 18.5679, lng: 73.9143, address: 'Symbiosis Road, Viman Nagar, Pune 411014', landmark: 'Phoenix Marketcity Pune' },
  { label: 'Baner High Street', city: 'Pune', lat: 18.5590, lng: 73.7868, address: 'Balewadi High Street, Baner, Pune 411045', landmark: 'Pancard Club Road' },

  // Delhi NCR
  { label: 'Connaught Place Central', city: 'Delhi', lat: 28.6315, lng: 77.2167, address: 'Inner Circle, Block C, Connaught Place, New Delhi 110001', landmark: 'Palika Bazar' },
  { label: 'Gurugram Cyber City', city: 'Delhi', lat: 28.4950, lng: 77.0895, address: 'DLF Cyber City, Building 10, Gurugram, HR 122002', landmark: 'Cyber Hub' },
  { label: 'Noida Sector 62 IT Park', city: 'Delhi', lat: 28.6280, lng: 77.3649, address: 'C-Block, Electronic City, Sector 62, Noida, UP 201309', landmark: 'Fortis Hospital' },
  { label: 'Nehru Place Hardware Hub', city: 'Delhi', lat: 28.5492, lng: 77.2533, address: 'Eros Corporate Tower, Nehru Place, New Delhi 110019', landmark: 'Nehru Place Metro' },

  // Bengaluru
  { label: 'Koramangala 5th Block', city: 'Bengaluru', lat: 12.9352, lng: 77.6245, address: '80 Feet Road, Koramangala 5th Block, Bengaluru, KA 560095', landmark: 'Koramangala Sony Signal' },
  { label: 'Indiranagar 100ft Road', city: 'Bengaluru', lat: 12.9784, lng: 77.6408, address: '100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru 560038', landmark: 'Domlur Flyover' },
  { label: 'Whitefield ITPL Tech Zone', city: 'Bengaluru', lat: 12.9863, lng: 77.7340, address: 'International Tech Park, Whitefield Main Road, Bengaluru 560066', landmark: 'ITPL Main Gate' },
  { label: 'Electronic City Phase 1', city: 'Bengaluru', lat: 12.8452, lng: 77.6602, address: 'Hosur Road, Electronic City Phase 1, Bengaluru 560100', landmark: 'Wipro Gate 5' },
];

export const SEED_DRIVERS: Driver[] = [
  {
    id: 'drv-1',
    name: 'Rahul Sharma',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    vehicleId: 'veh-1',
    vehiclePlate: 'MH-02-EE-2045',
    phone: '+91 98204 11290',
    currentLocation: { lat: 19.128, lng: 72.835, address: 'Andheri Link Road, Mumbai', landmark: 'Near Infiniti Mall' },
    status: 'available',
    rating: 4.95,
    completedDeliveriesToday: 6,
    totalCompletedDeliveries: 1420,
    currentWorkload: 35,
    maxDailyDeliveries: 16,
    drivingHoursToday: 4.2,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-2',
    name: 'Vikram Singh',
    companyId: 'comp-2',
    companyName: 'BlueDart Express',
    vehicleId: 'veh-2',
    vehiclePlate: 'MH-03-BX-8812',
    phone: '+91 97112 44331',
    currentLocation: { lat: 19.068, lng: 72.865, address: 'BKC Central Avenue, Mumbai', landmark: 'Near Bharat Diamond Bourse' },
    status: 'available',
    rating: 4.88,
    completedDeliveriesToday: 5,
    totalCompletedDeliveries: 980,
    currentWorkload: 40,
    maxDailyDeliveries: 14,
    drivingHoursToday: 3.8,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-3',
    name: 'Priya Patel',
    companyId: 'comp-6',
    companyName: 'GreenMile EV Fleet',
    vehicleId: 'veh-6',
    vehiclePlate: 'MH-01-EV-3001',
    phone: '+91 99208 77652',
    currentLocation: { lat: 19.112, lng: 72.848, address: 'Vile Parle East, Mumbai', landmark: 'Near Domestic Airport' },
    status: 'available',
    rating: 4.98,
    completedDeliveriesToday: 7,
    totalCompletedDeliveries: 1150,
    currentWorkload: 25,
    maxDailyDeliveries: 15,
    drivingHoursToday: 4.5,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-4',
    name: 'Amit Verma',
    companyId: 'comp-3',
    companyName: 'Delhivery Fleet',
    vehicleId: 'veh-3',
    vehiclePlate: 'MH-04-DL-9934',
    phone: '+91 98451 22908',
    currentLocation: { lat: 19.015, lng: 72.845, address: 'Dadar TT Circle, Mumbai', landmark: 'Near Swami Narayan Temple' },
    status: 'available',
    rating: 4.79,
    completedDeliveriesToday: 4,
    totalCompletedDeliveries: 840,
    currentWorkload: 55,
    maxDailyDeliveries: 12,
    drivingHoursToday: 5.1,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-5',
    name: 'Rajesh Kumar',
    companyId: 'comp-4',
    companyName: 'UrbanGo Logistics',
    vehicleId: 'veh-4',
    vehiclePlate: 'MH-02-UG-5510',
    phone: '+91 98110 33892',
    currentLocation: { lat: 19.118, lng: 72.905, address: 'Hiranandani Gardens, Powai, Mumbai', landmark: 'Near Galleria' },
    status: 'available',
    rating: 4.92,
    completedDeliveriesToday: 8,
    totalCompletedDeliveries: 1650,
    currentWorkload: 45,
    maxDailyDeliveries: 18,
    drivingHoursToday: 5.4,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-6',
    name: 'Sneha Nair',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    vehicleId: 'veh-7',
    vehiclePlate: 'MH-02-SW-1102',
    phone: '+91 97654 88123',
    currentLocation: { lat: 19.075, lng: 72.875, address: 'Kurla West, Mumbai', landmark: 'LBS Marg Junction' },
    status: 'available',
    rating: 4.89,
    completedDeliveriesToday: 5,
    totalCompletedDeliveries: 720,
    currentWorkload: 30,
    maxDailyDeliveries: 14,
    drivingHoursToday: 3.5,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-7',
    name: 'Mohammed Farhan',
    companyId: 'comp-5',
    companyName: 'RapidRoute Parcel',
    vehicleId: 'veh-5',
    vehiclePlate: 'MH-03-RR-7721',
    phone: '+91 98921 55670',
    currentLocation: { lat: 18.995, lng: 72.832, address: 'Lower Parel, Mumbai', landmark: 'Senapati Bapat Marg' },
    status: 'delivering',
    rating: 4.75,
    completedDeliveriesToday: 4,
    totalCompletedDeliveries: 610,
    currentWorkload: 75,
    maxDailyDeliveries: 12,
    drivingHoursToday: 6.2,
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-8',
    name: 'Suresh Deshmukh',
    companyId: 'comp-7',
    companyName: 'MetroParcel Co.',
    vehicleId: 'veh-8',
    vehiclePlate: 'MH-43-MP-4409',
    phone: '+91 98231 66789',
    currentLocation: { lat: 19.079, lng: 72.995, address: 'Sector 17, Vashi, Navi Mumbai', landmark: 'Palm Beach Road' },
    status: 'available',
    rating: 4.82,
    completedDeliveriesToday: 3,
    totalCompletedDeliveries: 540,
    currentWorkload: 20,
    maxDailyDeliveries: 10,
    drivingHoursToday: 2.8,
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-9',
    name: 'Karan Mehra',
    companyId: 'comp-8',
    companyName: 'Apex SuperTrans',
    vehicleId: 'veh-9',
    vehiclePlate: 'MH-04-AP-9901',
    phone: '+91 99104 22345',
    currentLocation: { lat: 19.215, lng: 72.975, address: 'Ghodbunder Road, Thane', landmark: 'Near Majiwada Flyover' },
    status: 'available',
    rating: 4.86,
    completedDeliveriesToday: 4,
    totalCompletedDeliveries: 780,
    currentWorkload: 40,
    maxDailyDeliveries: 12,
    drivingHoursToday: 4.1,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-10',
    name: 'Deepak Joshi',
    companyId: 'comp-6',
    companyName: 'GreenMile EV Fleet',
    vehicleId: 'veh-10',
    vehiclePlate: 'MH-01-GM-8822',
    phone: '+91 98670 44512',
    currentLocation: { lat: 18.928, lng: 72.825, address: 'Nariman Point, Mumbai', landmark: 'Near CR2 Mall' },
    status: 'available',
    rating: 4.96,
    completedDeliveriesToday: 6,
    totalCompletedDeliveries: 1320,
    currentWorkload: 30,
    maxDailyDeliveries: 15,
    drivingHoursToday: 4.0,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-11',
    name: 'Anand Shinde',
    companyId: 'comp-9',
    companyName: 'SpeedX Express',
    vehicleId: 'veh-11',
    vehiclePlate: 'MH-02-SX-3304',
    phone: '+91 97731 55901',
    currentLocation: { lat: 19.185, lng: 72.835, address: 'Malad Link Road, Mumbai', landmark: 'Near Infinity 2' },
    status: 'break',
    rating: 4.65,
    completedDeliveriesToday: 5,
    totalCompletedDeliveries: 490,
    currentWorkload: 50,
    maxDailyDeliveries: 14,
    drivingHoursToday: 5.0,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-12',
    name: 'Rohan Gupta',
    companyId: 'comp-10',
    companyName: 'Zenith Courier Hub',
    vehicleId: 'veh-12',
    vehiclePlate: 'MH-01-ZN-7711',
    phone: '+91 99872 33456',
    currentLocation: { lat: 19.018, lng: 72.819, address: 'Worli Naka, Mumbai', landmark: 'Dr Annie Besant Road' },
    status: 'available',
    rating: 4.84,
    completedDeliveriesToday: 4,
    totalCompletedDeliveries: 670,
    currentWorkload: 35,
    maxDailyDeliveries: 12,
    drivingHoursToday: 3.9,
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-13',
    name: 'Manish Pandey',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    vehicleId: 'veh-13',
    vehiclePlate: 'MH-02-SW-9022',
    phone: '+91 98190 22187',
    currentLocation: { lat: 19.165, lng: 72.858, address: 'Goregaon East Nesco, Mumbai', landmark: 'Western Express Highway' },
    status: 'available',
    rating: 4.91,
    completedDeliveriesToday: 7,
    totalCompletedDeliveries: 1540,
    currentWorkload: 40,
    maxDailyDeliveries: 16,
    drivingHoursToday: 4.8,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-14',
    name: 'Gaurav Kulkarni',
    companyId: 'comp-2',
    companyName: 'BlueDart Express',
    vehicleId: 'veh-14',
    vehiclePlate: 'MH-03-BD-4419',
    phone: '+91 98205 66782',
    currentLocation: { lat: 19.055, lng: 72.901, address: 'Chembur East, Mumbai', landmark: 'Diamond Garden Circle' },
    status: 'available',
    rating: 4.81,
    completedDeliveriesToday: 5,
    totalCompletedDeliveries: 890,
    currentWorkload: 45,
    maxDailyDeliveries: 14,
    drivingHoursToday: 4.4,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-15',
    name: 'Santosh Yadav',
    companyId: 'comp-3',
    companyName: 'Delhivery Fleet',
    vehicleId: 'veh-15',
    vehiclePlate: 'MH-04-DL-1188',
    phone: '+91 98452 77190',
    currentLocation: { lat: 18.908, lng: 72.815, address: 'Colaba, Mumbai', landmark: 'Cuffe Parade Terminal' },
    status: 'available',
    rating: 4.76,
    completedDeliveriesToday: 3,
    totalCompletedDeliveries: 560,
    currentWorkload: 30,
    maxDailyDeliveries: 10,
    drivingHoursToday: 3.1,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'drv-16',
    name: 'Nitin Sawant',
    companyId: 'comp-6',
    companyName: 'GreenMile EV Fleet',
    phone: '+91 98211 44556',
    currentLocation: { lat: 19.105, lng: 72.828, address: 'Juhu Beach Road, Mumbai', landmark: 'Near ISKCON Temple' },
    status: 'offline',
    rating: 4.78,
    completedDeliveriesToday: 8,
    totalCompletedDeliveries: 920,
    currentWorkload: 10,
    maxDailyDeliveries: 15,
    drivingHoursToday: 8.8,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    plateNumber: 'EV-204 (MH-02-EE-2045)',
    vehicleType: 'ev_van',
    fuelType: 'electric',
    capacityKg: 850,
    currentLoadKg: 120,
    availableCapacityKg: 730,
    operatingCostPerKm: 4.8,
    currentLocation: { lat: 19.131, lng: 72.832, address: 'Lokhandwala Andheri W, Mumbai', landmark: 'Andheri Depot' },
    status: 'available',
    driverId: 'drv-1',
    driverName: 'Rahul Sharma',
    maxRangeKm: 240,
    batteryOrFuelPct: 88,
    speedKmh: 42,
  },
  {
    id: 'veh-2',
    companyId: 'comp-2',
    companyName: 'BlueDart Express',
    plateNumber: 'MH-03-BX-8812',
    vehicleType: 'van',
    fuelType: 'cng',
    capacityKg: 650,
    currentLoadKg: 340,
    availableCapacityKg: 310,
    operatingCostPerKm: 7.2,
    currentLocation: { lat: 19.068, lng: 72.865, address: 'BKC Central, Mumbai', landmark: 'G Block Hub' },
    status: 'available',
    driverId: 'drv-2',
    driverName: 'Vikram Singh',
    maxRangeKm: 320,
    batteryOrFuelPct: 75,
    speedKmh: 38,
  },
  {
    id: 'veh-3',
    companyId: 'comp-3',
    companyName: 'Delhivery Fleet',
    plateNumber: 'MH-04-DL-9934',
    vehicleType: 'mini_truck',
    fuelType: 'diesel',
    capacityKg: 1400,
    currentLoadKg: 950,
    availableCapacityKg: 450,
    operatingCostPerKm: 11.5,
    currentLocation: { lat: 19.015, lng: 72.845, address: 'Dadar TT, Mumbai', landmark: 'Dadar Cargo Hub' },
    status: 'available',
    driverId: 'drv-4',
    driverName: 'Amit Verma',
    maxRangeKm: 450,
    batteryOrFuelPct: 62,
    speedKmh: 35,
  },
  {
    id: 'veh-4',
    companyId: 'comp-4',
    companyName: 'UrbanGo Logistics',
    plateNumber: 'MH-02-UG-5510',
    vehicleType: 'bike',
    fuelType: 'petrol',
    capacityKg: 20,
    currentLoadKg: 4,
    availableCapacityKg: 16,
    operatingCostPerKm: 2.8,
    currentLocation: { lat: 19.118, lng: 72.905, address: 'Powai Tech City, Mumbai', landmark: 'Galleria Mall' },
    status: 'available',
    driverId: 'drv-5',
    driverName: 'Rajesh Kumar',
    maxRangeKm: 180,
    batteryOrFuelPct: 80,
    speedKmh: 45,
  },
  {
    id: 'veh-5',
    companyId: 'comp-5',
    companyName: 'RapidRoute Parcel',
    plateNumber: 'MH-03-RR-7721',
    vehicleType: 'van',
    fuelType: 'diesel',
    capacityKg: 750,
    currentLoadKg: 620,
    availableCapacityKg: 130,
    operatingCostPerKm: 8.5,
    currentLocation: { lat: 18.995, lng: 72.832, address: 'Lower Parel, Mumbai', landmark: 'Senapati Bapat Hub' },
    status: 'delivering',
    driverId: 'drv-7',
    driverName: 'Mohammed Farhan',
    maxRangeKm: 380,
    batteryOrFuelPct: 45,
    speedKmh: 28,
  },
  {
    id: 'veh-6',
    companyId: 'comp-6',
    companyName: 'GreenMile EV Fleet',
    plateNumber: 'MH-01-EV-3001',
    vehicleType: 'ev_van',
    fuelType: 'electric',
    capacityKg: 950,
    currentLoadKg: 80,
    availableCapacityKg: 870,
    operatingCostPerKm: 4.2,
    currentLocation: { lat: 19.112, lng: 72.848, address: 'Vile Parle East, Mumbai', landmark: 'Airport Hub' },
    status: 'available',
    driverId: 'drv-3',
    driverName: 'Priya Patel',
    maxRangeKm: 280,
    batteryOrFuelPct: 94,
    speedKmh: 40,
  },
  {
    id: 'veh-7',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    plateNumber: 'MH-02-SW-1102',
    vehicleType: 'scooter',
    fuelType: 'electric',
    capacityKg: 25,
    currentLoadKg: 5,
    availableCapacityKg: 20,
    operatingCostPerKm: 1.9,
    currentLocation: { lat: 19.075, lng: 72.875, address: 'Kurla West, Mumbai', landmark: 'LBS Road' },
    status: 'available',
    driverId: 'drv-6',
    driverName: 'Sneha Nair',
    maxRangeKm: 120,
    batteryOrFuelPct: 90,
    speedKmh: 35,
  },
  {
    id: 'veh-8',
    companyId: 'comp-7',
    companyName: 'MetroParcel Co.',
    plateNumber: 'MH-43-MP-4409',
    vehicleType: 'truck',
    fuelType: 'diesel',
    capacityKg: 4500,
    currentLoadKg: 2100,
    availableCapacityKg: 2400,
    operatingCostPerKm: 18.0,
    currentLocation: { lat: 19.079, lng: 72.995, address: 'Vashi Sector 17, Navi Mumbai', landmark: 'APMC Logistics Yard' },
    status: 'available',
    driverId: 'drv-8',
    driverName: 'Suresh Deshmukh',
    maxRangeKm: 600,
    batteryOrFuelPct: 70,
    speedKmh: 40,
  },
  {
    id: 'veh-9',
    companyId: 'comp-8',
    companyName: 'Apex SuperTrans',
    plateNumber: 'MH-04-AP-9901',
    vehicleType: 'mini_truck',
    fuelType: 'cng',
    capacityKg: 1200,
    currentLoadKg: 400,
    availableCapacityKg: 800,
    operatingCostPerKm: 9.8,
    currentLocation: { lat: 19.215, lng: 72.975, address: 'Ghodbunder Road, Thane', landmark: 'Thane Central Depot' },
    status: 'available',
    driverId: 'drv-9',
    driverName: 'Karan Mehra',
    maxRangeKm: 340,
    batteryOrFuelPct: 65,
    speedKmh: 36,
  },
  {
    id: 'veh-10',
    companyId: 'comp-6',
    companyName: 'GreenMile EV Fleet',
    plateNumber: 'MH-01-GM-8822',
    vehicleType: 'ev_van',
    fuelType: 'electric',
    capacityKg: 800,
    currentLoadKg: 150,
    availableCapacityKg: 650,
    operatingCostPerKm: 4.5,
    currentLocation: { lat: 18.928, lng: 72.825, address: 'Nariman Point, Mumbai', landmark: 'Free Press Marg' },
    status: 'available',
    driverId: 'drv-10',
    driverName: 'Deepak Joshi',
    maxRangeKm: 260,
    batteryOrFuelPct: 82,
    speedKmh: 38,
  },
  {
    id: 'veh-11',
    companyId: 'comp-9',
    companyName: 'SpeedX Express',
    plateNumber: 'MH-02-SX-3304',
    vehicleType: 'bike',
    fuelType: 'petrol',
    capacityKg: 18,
    currentLoadKg: 2,
    availableCapacityKg: 16,
    operatingCostPerKm: 2.6,
    currentLocation: { lat: 19.185, lng: 72.835, address: 'Malad Link Road, Mumbai', landmark: 'Inorbit Yard' },
    status: 'offline',
    driverId: 'drv-11',
    driverName: 'Anand Shinde',
    maxRangeKm: 160,
    batteryOrFuelPct: 55,
    speedKmh: 0,
  },
  {
    id: 'veh-12',
    companyId: 'comp-10',
    companyName: 'Zenith Courier Hub',
    plateNumber: 'MH-01-ZN-7711',
    vehicleType: 'van',
    fuelType: 'diesel',
    capacityKg: 700,
    currentLoadKg: 300,
    availableCapacityKg: 400,
    operatingCostPerKm: 8.0,
    currentLocation: { lat: 19.018, lng: 72.819, address: 'Worli Seaface, Mumbai', landmark: 'Worli Hub' },
    status: 'available',
    driverId: 'drv-12',
    driverName: 'Rohan Gupta',
    maxRangeKm: 360,
    batteryOrFuelPct: 78,
    speedKmh: 34,
  },
  {
    id: 'veh-13',
    companyId: 'comp-1',
    companyName: 'SwiftShip Logistics',
    plateNumber: 'MH-02-SW-9022',
    vehicleType: 'ev_van',
    fuelType: 'electric',
    capacityKg: 900,
    currentLoadKg: 210,
    availableCapacityKg: 690,
    operatingCostPerKm: 4.6,
    currentLocation: { lat: 19.165, lng: 72.858, address: 'Goregaon East Nesco, Mumbai', landmark: 'Nesco Western Hub' },
    status: 'available',
    driverId: 'drv-13',
    driverName: 'Manish Pandey',
    maxRangeKm: 250,
    batteryOrFuelPct: 91,
    speedKmh: 42,
  },
  {
    id: 'veh-14',
    companyId: 'comp-2',
    companyName: 'BlueDart Express',
    plateNumber: 'MH-03-BD-4419',
    vehicleType: 'scooter',
    fuelType: 'electric',
    capacityKg: 25,
    currentLoadKg: 8,
    availableCapacityKg: 17,
    operatingCostPerKm: 2.1,
    currentLocation: { lat: 19.055, lng: 72.901, address: 'Chembur East, Mumbai', landmark: 'Diamond Garden Hub' },
    status: 'available',
    driverId: 'drv-14',
    driverName: 'Gaurav Kulkarni',
    maxRangeKm: 110,
    batteryOrFuelPct: 84,
    speedKmh: 36,
  },
  {
    id: 'veh-15',
    companyId: 'comp-3',
    companyName: 'Delhivery Fleet',
    plateNumber: 'MH-04-DL-1188',
    vehicleType: 'truck',
    fuelType: 'diesel',
    capacityKg: 5000,
    currentLoadKg: 4900,
    availableCapacityKg: 100,
    operatingCostPerKm: 19.5,
    currentLocation: { lat: 18.908, lng: 72.815, address: 'Colaba, Mumbai', landmark: 'Cuffe Parade Cargo' },
    status: 'maintenance',
    driverId: 'drv-15',
    driverName: 'Santosh Yadav',
    maxRangeKm: 650,
    batteryOrFuelPct: 30,
    speedKmh: 0,
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'ORD-2026-8810',
    customerId: 'user-customer',
    customerName: 'Omkar Mane',
    customerPhone: '+91 98334 12890',
    sender: {
      name: 'Mumbai Electronics Logistics',
      phone: '+91 98201 99012',
      location: {
        lat: 19.1363,
        lng: 72.8277,
        address: 'Lokhandwala Complex, Andheri West, Mumbai, MH 400053',
        landmark: 'Infinity Mall Warehouse',
        city: 'Mumbai',
      },
    },
    recipient: {
      name: 'Bandra FinTech Solutions',
      phone: '+91 98112 33451',
      location: {
        lat: 19.0657,
        lng: 72.8687,
        address: 'G Block, BKC Financial Center, Bandra East, Mumbai 400051',
        landmark: 'One BKC Tower B',
        city: 'Mumbai',
      },
    },
    package: {
      id: 'pkg-101',
      type: 'electronics',
      weightKg: 12.0,
      dimensionsCm: { length: 45, width: 35, height: 25 },
      quantity: 2,
      fragile: true,
      temperatureSensitive: false,
      hazardous: false,
      specialInstructions: 'Handle with care - server network cards and optical switches',
      declaredValueInr: 85000,
    },
    deliveryWindow: {
      type: 'express',
      startTime: '14:00',
      endTime: '15:30',
      maxAcceptableMinutes: 60,
      priorityScore: 9,
    },
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    estimatedDistanceKm: 14.8,
    estimatedTravelTimeMin: 28,
    estimatedCostInr: 145,
  },
  {
    id: 'ord-102',
    orderNumber: 'ORD-2026-8811',
    customerId: 'user-customer',
    customerName: 'Apex HealthCare Diagnostics',
    customerPhone: '+91 98450 11992',
    sender: {
      name: 'Central Diagnostic Lab',
      phone: '+91 98205 33210',
      location: {
        lat: 19.0178,
        lng: 72.8478,
        address: 'Dr. Babasaheb Ambedkar Road, Dadar TT, Mumbai 400014',
        landmark: 'Near Tata Memorial Hub',
        city: 'Mumbai',
      },
    },
    recipient: {
      name: 'Lower Parel Specialty Clinic',
      phone: '+91 98209 88123',
      location: {
        lat: 18.9934,
        lng: 72.8315,
        address: 'Senapati Bapat Marg, Lower Parel, Mumbai 400013',
        landmark: 'High Street Phoenix Medical Suite',
        city: 'Mumbai',
      },
    },
    package: {
      id: 'pkg-102',
      type: 'medical',
      weightKg: 4.5,
      dimensionsCm: { length: 30, width: 20, height: 18 },
      quantity: 1,
      fragile: true,
      temperatureSensitive: true,
      hazardous: false,
      specialInstructions: 'Temperature controlled thermal box (2-8°C)',
      declaredValueInr: 32000,
    },
    deliveryWindow: {
      type: 'same_day',
      startTime: '11:00',
      endTime: '12:15',
      maxAcceptableMinutes: 45,
      priorityScore: 10,
    },
    status: 'assigned',
    assignedCompanyId: 'comp-1',
    assignedCompanyName: 'SwiftShip Logistics',
    assignedVehicleId: 'veh-1',
    assignedVehiclePlate: 'EV-204 (MH-02-EE-2045)',
    assignedVehicleType: 'ev_van',
    assignedDriverId: 'drv-1',
    assignedDriverName: 'Rahul Sharma',
    assignedDriverPhone: '+91 98204 11290',
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    estimatedDistanceKm: 5.2,
    estimatedTravelTimeMin: 18,
    estimatedCostInr: 68,
    optimizationScore: 94.6,
  },
  {
    id: 'ord-103',
    orderNumber: 'ORD-2026-8812',
    customerId: 'user-customer',
    customerName: 'Hiranandani Corporate Supplies',
    customerPhone: '+91 98765 43210',
    sender: {
      name: 'Powai Industrial Estate',
      phone: '+91 98110 55432',
      location: {
        lat: 19.1176,
        lng: 72.9060,
        address: 'Hiranandani Business Park, Powai, Mumbai 400076',
        landmark: 'Supreme City Complex',
        city: 'Mumbai',
      },
    },
    recipient: {
      name: 'Goregaon IT Campus',
      phone: '+91 98332 11987',
      location: {
        lat: 19.1663,
        lng: 72.8596,
        address: 'Nesco Center, Western Express Highway, Goregaon East 400063',
        landmark: 'Nesco Tower 4',
        city: 'Mumbai',
      },
    },
    package: {
      id: 'pkg-103',
      type: 'general_cargo',
      weightKg: 85.0,
      dimensionsCm: { length: 120, width: 80, height: 60 },
      quantity: 5,
      fragile: false,
      temperatureSensitive: false,
      hazardous: false,
      specialInstructions: 'Commercial workstation hardware pallets',
      declaredValueInr: 140000,
    },
    deliveryWindow: {
      type: 'standard',
      startTime: '10:00',
      endTime: '16:00',
      maxAcceptableMinutes: 180,
      priorityScore: 6,
    },
    status: 'in_transit',
    assignedCompanyId: 'comp-4',
    assignedCompanyName: 'UrbanGo Logistics',
    assignedVehicleId: 'veh-4',
    assignedVehiclePlate: 'MH-02-UG-5510',
    assignedVehicleType: 'bike',
    assignedDriverId: 'drv-5',
    assignedDriverName: 'Rajesh Kumar',
    assignedDriverPhone: '+91 98110 33892',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    estimatedDistanceKm: 12.4,
    estimatedTravelTimeMin: 25,
    estimatedCostInr: 120,
    optimizationScore: 89.2,
  },
  {
    id: 'ord-104',
    orderNumber: 'ORD-2026-8813',
    customerId: 'user-customer',
    customerName: 'Navi Mumbai Retailers Group',
    customerPhone: '+91 99201 44512',
    sender: {
      name: 'Vashi Wholesale Mart',
      phone: '+91 98231 66789',
      location: {
        lat: 19.0771,
        lng: 72.9986,
        address: 'Sector 17, Vashi, Navi Mumbai 400703',
        landmark: 'Inorbit Mall Vashi',
        city: 'Mumbai',
      },
    },
    recipient: {
      name: 'Nariman Point Boutique',
      phone: '+91 98670 44512',
      location: {
        lat: 18.9256,
        lng: 72.8242,
        address: 'Free Press Journal Marg, Nariman Point, Mumbai 400021',
        landmark: 'Air India Building',
        city: 'Mumbai',
      },
    },
    package: {
      id: 'pkg-104',
      type: 'apparel',
      weightKg: 22.0,
      dimensionsCm: { length: 60, width: 50, height: 40 },
      quantity: 3,
      fragile: false,
      temperatureSensitive: false,
      hazardous: false,
      specialInstructions: 'Dry carton boxed apparel',
      declaredValueInr: 45000,
    },
    deliveryWindow: {
      type: 'express',
      startTime: '13:00',
      endTime: '15:00',
      maxAcceptableMinutes: 75,
      priorityScore: 8,
    },
    status: 'delivered',
    assignedCompanyId: 'comp-6',
    assignedCompanyName: 'GreenMile EV Fleet',
    assignedVehicleId: 'veh-10',
    assignedVehiclePlate: 'MH-01-GM-8822',
    assignedVehicleType: 'ev_van',
    assignedDriverId: 'drv-10',
    assignedDriverName: 'Deepak Joshi',
    assignedDriverPhone: '+91 98670 44512',
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    estimatedDistanceKm: 31.5,
    estimatedTravelTimeMin: 48,
    estimatedCostInr: 215,
    optimizationScore: 92.4,
  },
];

export const SEED_SYSTEM_EVENTS: SystemEvent[] = [
  {
    id: 'evt-1',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    type: 'ORDER_CREATED',
    title: 'Order ORD-2026-8810 Logged',
    description: 'High priority 12 kg electronics delivery registered from Andheri West to BKC.',
    severity: 'info',
    orderId: 'ord-101',
  },
  {
    id: 'evt-2',
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    type: 'ORDER_ASSIGNED',
    title: 'Optimal Fleet Match Selected',
    description: 'Vehicle EV-204 (Driver Rahul Sharma) assigned with 94.6 composite score.',
    severity: 'success',
    orderId: 'ord-102',
    vehicleId: 'veh-1',
    driverId: 'drv-1',
  },
  {
    id: 'evt-3',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    type: 'ROUTE_CONFLICT_DETECTED',
    title: 'Shared Corridor Warning on S.V. Road',
    description: 'Intersection overlap flagged between MH-02-EE-2045 and MH-03-BX-8812. Advisory reroute queued.',
    severity: 'warning',
    vehicleId: 'veh-1',
  },
  {
    id: 'evt-4',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Confirmed for ORD-2026-8813',
    description: 'Parcel safely delivered at Nariman Point. 12 minutes ahead of schedule. Carbon offset: 2.8 kg CO2.',
    severity: 'success',
    orderId: 'ord-104',
    vehicleId: 'veh-10',
    driverId: 'drv-10',
  },
];

export const SEED_CONFLICTS: RouteConflict[] = [
  {
    id: 'conflict-1',
    vehicleAId: 'veh-1',
    vehicleAPlate: 'EV-204 (MH-02-EE-2045)',
    vehicleBId: 'veh-2',
    vehicleBPlate: 'MH-03-BX-8812',
    sharedSegment: 'Andheri West S.V. Road ↔ Bandra Linking Road',
    location: [19.098, 72.842],
    severity: 'high',
    detectedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    status: 'active',
    recommendedAction: 'Shift MH-03-BX-8812 to Western Express Highway Flyover. Estimated time saved: 7 minutes.',
    estimatedTimeSavedMin: 7,
  },
  {
    id: 'conflict-2',
    vehicleAId: 'veh-3',
    vehicleAPlate: 'MH-04-DL-9934',
    vehicleBId: 'veh-5',
    vehicleBPlate: 'MH-03-RR-7721',
    sharedSegment: 'Lower Parel Senapati Bapat Marg Junction',
    location: [18.998, 72.833],
    severity: 'medium',
    detectedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    status: 'active',
    recommendedAction: 'Reroute MH-04-DL-9934 via Dr. E Moses Road elevated bypass.',
    estimatedTimeSavedMin: 5,
  },
];
